import { LabTest, MedicalStore, HealthPackage, Appointment, Notification, Banner } from '../types';
import { DOCTORS } from '../../../../apps/patient/src/features/doctor/services/doctorData';

// ============================================
// LAB TESTS DATA
// ============================================

export const LAB_TESTS: LabTest[] = [
  {
    id: 'lt1',
    name: 'Complete Blood Count (CBC)',
    category: 'Blood Tests',
    price: 350,
    discountPercent: 20,
    discountedPrice: 280,
    reportTime: '6 hours',
    description: 'A CBC test measures the different components of blood including red blood cells, white blood cells, platelets, hemoglobin, and hematocrit.',
    preparation: ['No special preparation needed', 'Stay hydrated', 'Inform about current medications'],
    includes: ['Hemoglobin', 'WBC Count', 'RBC Count', 'Platelet Count', 'MCV', 'MCH', 'MCHC', 'Differential Count'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/F44336/white?text=CBC',
  },
  {
    id: 'lt2',
    name: 'Blood Sugar (Fasting)',
    category: 'Diabetes',
    price: 80,
    discountPercent: 15,
    discountedPrice: 68,
    reportTime: '3 hours',
    description: 'Fasting blood glucose test measures blood sugar levels after an overnight fast. Used to diagnose diabetes and prediabetes.',
    preparation: ['Fast for 8-12 hours', 'Water is allowed', 'No exercise before test', 'Avoid smoking'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/FF9800/white?text=BSF',
  },
  {
    id: 'lt3',
    name: 'Thyroid Profile (T3, T4, TSH)',
    category: 'Thyroid',
    price: 450,
    discountPercent: 25,
    discountedPrice: 337.5,
    reportTime: '12 hours',
    description: 'Complete thyroid profile measures T3 (triiodothyronine), T4 (thyroxine), and TSH (thyroid stimulating hormone) to assess thyroid function.',
    preparation: ['Morning sample preferred', 'No special fasting required', 'Inform about thyroid medications', 'Avoid biotin supplements for 2 days'],
    includes: ['T3 (Total)', 'T4 (Total)', 'TSH (Ultrasensitive)'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/9C27B0/white?text=THY',
  },
  {
    id: 'lt4',
    name: 'Vitamin D (25-OH)',
    category: 'Vitamins',
    price: 900,
    discountPercent: 30,
    discountedPrice: 630,
    reportTime: '24 hours',
    description: 'Measures the level of Vitamin D in the blood. Essential for assessing bone health, immune function, and risk of vitamin D deficiency.',
    preparation: ['No fasting required', 'Inform about supplements being taken', 'Morning sample preferred'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/FFEB3B/black?text=VD3',
  },
  {
    id: 'lt5',
    name: 'Vitamin B12',
    category: 'Vitamins',
    price: 650,
    discountPercent: 20,
    discountedPrice: 520,
    reportTime: '24 hours',
    description: 'Measures Vitamin B12 levels in blood. Important for nerve function, red blood cell production, and DNA synthesis.',
    preparation: ['No fasting required', 'Avoid B12 supplements for 24 hours', 'Inform about medications'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/E91E63/white?text=B12',
  },
  {
    id: 'lt6',
    name: 'Urine Routine & Microscopy',
    category: 'Urine Tests',
    price: 120,
    discountPercent: 10,
    discountedPrice: 108,
    reportTime: '4 hours',
    description: 'Complete urine analysis examining physical, chemical, and microscopic properties to detect kidney disease, infections, and diabetes.',
    preparation: ['Collect mid-stream urine', 'Use sterile container', 'First morning urine preferred', 'Do not collect during menstruation'],
    includes: ['Color', 'Clarity', 'pH', 'Protein', 'Glucose', 'Ketones', 'Bilirubin', 'Blood', 'WBC', 'RBC', 'Casts', 'Crystals'],
    isPopular: false,
    image: 'https://via.placeholder.com/150/2196F3/white?text=URN',
  },
  {
    id: 'lt7',
    name: 'ECG (Electrocardiogram)',
    category: 'Cardiac',
    price: 300,
    discountPercent: 15,
    discountedPrice: 255,
    reportTime: 'Immediate',
    description: 'An ECG records the electrical signals in the heart to check for heart conditions. Non-invasive and takes about 10 minutes.',
    preparation: ['Wear comfortable clothing', 'Avoid applying lotions or oils on chest', 'Inform about pacemaker if any', 'Relax before the test'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/F44336/white?text=ECG',
  },
  {
    id: 'lt8',
    name: 'X-Ray Chest (PA View)',
    category: 'Imaging',
    price: 350,
    discountPercent: 10,
    discountedPrice: 315,
    reportTime: '2 hours',
    description: 'Chest X-ray provides images of the heart, lungs, airways, blood vessels, and bones of the spine and chest.',
    preparation: ['Remove metal jewelry', 'Inform if pregnant', 'Wear loose comfortable clothing', 'Remove piercings'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/607D8B/white?text=XRY',
  },
  {
    id: 'lt9',
    name: 'CT Scan Chest',
    category: 'Imaging',
    price: 4500,
    discountPercent: 20,
    discountedPrice: 3600,
    reportTime: '24 hours',
    description: 'CT scan of the chest provides detailed cross-sectional images of chest structures including lungs, heart, and blood vessels.',
    preparation: ['Remove metal objects', 'Inform about allergies if contrast is used', 'May need to fast for 4 hours', 'Inform if pregnant'],
    isPopular: false,
    image: 'https://via.placeholder.com/150/455A64/white?text=CT',
  },
  {
    id: 'lt10',
    name: 'MRI Brain',
    category: 'Imaging',
    price: 7500,
    discountPercent: 15,
    discountedPrice: 6375,
    reportTime: '48 hours',
    description: 'MRI scan of the brain provides detailed images using magnetic fields and radio waves. Detects tumors, stroke, and other brain conditions.',
    preparation: ['Remove all metal objects', 'Inform about implants/pacemaker', 'Inform if claustrophobic', 'Patients with tattoos should inform'],
    isPopular: false,
    image: 'https://via.placeholder.com/150/311B92/white?text=MRI',
  },
  {
    id: 'lt11',
    name: 'Ultrasound Abdomen',
    category: 'Imaging',
    price: 800,
    discountPercent: 10,
    discountedPrice: 720,
    reportTime: '3 hours',
    description: 'Abdominal ultrasound examines organs including liver, gallbladder, spleen, pancreas, kidneys, and bladder.',
    preparation: ['Fast for 4-6 hours', 'Drink 4-6 glasses of water before pelvic ultrasound', 'Wear comfortable clothing', 'Avoid gas-forming foods'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/00695C/white?text=USG',
  },
  {
    id: 'lt12',
    name: 'Lipid Profile',
    category: 'Blood Tests',
    price: 500,
    discountPercent: 25,
    discountedPrice: 375,
    reportTime: '6 hours',
    description: 'Lipid profile measures total cholesterol, LDL, HDL, and triglycerides to assess cardiovascular risk.',
    preparation: ['Fast for 9-12 hours', 'No alcohol for 24 hours', 'Avoid fatty foods for 2 days', 'Water is allowed'],
    includes: ['Total Cholesterol', 'LDL Cholesterol', 'HDL Cholesterol', 'VLDL Cholesterol', 'Triglycerides', 'Cholesterol/HDL ratio'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/D32F2F/white?text=LIP',
  },
  {
    id: 'lt13',
    name: 'Liver Function Test (LFT)',
    category: 'Blood Tests',
    price: 600,
    discountPercent: 20,
    discountedPrice: 480,
    reportTime: '8 hours',
    description: 'LFT measures proteins, liver enzymes, and bilirubin to assess liver health and detect liver disease or damage.',
    preparation: ['Fast for 8-12 hours', 'Avoid alcohol for 24 hours', 'Inform about medications', 'Avoid strenuous exercise'],
    includes: ['Bilirubin (Total/Direct/Indirect)', 'SGOT (AST)', 'SGPT (ALT)', 'Alkaline Phosphatase', 'Total Protein', 'Albumin', 'Globulin', 'GGTP'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/33691E/white?text=LFT',
  },
  {
    id: 'lt14',
    name: 'HbA1c (Glycated Hemoglobin)',
    category: 'Diabetes',
    price: 380,
    discountPercent: 15,
    discountedPrice: 323,
    reportTime: '6 hours',
    description: 'HbA1c measures average blood glucose levels over the past 2-3 months. Key test for diabetes monitoring and diagnosis.',
    preparation: ['No fasting required', 'Can be done any time of the day', 'Continue regular diet and medications'],
    isPopular: true,
    image: 'https://via.placeholder.com/150/1565C0/white?text=A1C',
  },
  {
    id: 'lt15',
    name: 'Kidney Function Test (KFT)',
    category: 'Blood Tests',
    price: 550,
    discountPercent: 20,
    discountedPrice: 440,
    reportTime: '8 hours',
    description: 'KFT evaluates kidney health by measuring creatinine, urea, uric acid, and electrolyte levels.',
    preparation: ['Fast for 8-12 hours', 'Stay well hydrated', 'Inform about medications', 'Avoid strenuous exercise'],
    includes: ['Blood Urea Nitrogen', 'Serum Creatinine', 'Uric Acid', 'Sodium', 'Potassium', 'Chloride', 'eGFR'],
    isPopular: false,
    image: 'https://via.placeholder.com/150/00838F/white?text=KFT',
  },
];

// ============================================
// MEDICAL STORES DATA
// ============================================

export const MEDICAL_STORES: MedicalStore[] = [
  {
    id: 'ms1',
    name: 'Apollo Pharmacy',
    address: '12, MG Road, Indiranagar, Bangalore - 560038',
    distance: '0.4 km',
    rating: 4.5,
    phone: '+91-80-41234567',
    isOpen: true,
    openTime: '7:00 AM',
    closeTime: '11:00 PM',
    image: 'https://via.placeholder.com/150/0066CC/white?text=AP',
    services: ['Home Delivery', 'Prescription Filling', '24/7 Available', 'Generic Medicines'],
  },
  {
    id: 'ms2',
    name: 'Medplus Health Services',
    address: '45, Koramangala Block 5, Bangalore - 560095',
    distance: '0.8 km',
    rating: 4.3,
    phone: '+91-80-25678901',
    isOpen: true,
    openTime: '8:00 AM',
    closeTime: '10:00 PM',
    image: 'https://via.placeholder.com/150/00A86B/white?text=MP',
    services: ['Lab Tests', 'Home Delivery', 'Generic Medicines', 'Health Products'],
  },
  {
    id: 'ms3',
    name: '1mg Store',
    address: '78, HSR Layout, Sector 4, Bangalore - 560102',
    distance: '1.2 km',
    rating: 4.6,
    phone: '+91-80-35678912',
    isOpen: false,
    openTime: '9:00 AM',
    closeTime: '9:00 PM',
    image: 'https://via.placeholder.com/150/E53935/white?text=1mg',
    services: ['Online Ordering', 'Doctor Consultation', 'Lab Tests', 'Health Records'],
  },
  {
    id: 'ms4',
    name: 'Wellness Forever',
    address: '23, JP Nagar 5th Phase, Bangalore - 560078',
    distance: '1.5 km',
    rating: 4.4,
    phone: '+91-80-45678923',
    isOpen: true,
    openTime: '8:30 AM',
    closeTime: '10:30 PM',
    image: 'https://via.placeholder.com/150/7B1FA2/white?text=WF',
    services: ['Ayurvedic Medicines', 'Health Supplements', 'Medical Equipment', 'Home Delivery'],
  },
  {
    id: 'ms5',
    name: 'Netmeds Store',
    address: '56, Jayanagar 4th Block, Bangalore - 560041',
    distance: '2.0 km',
    rating: 4.2,
    phone: '+91-80-55678934',
    isOpen: true,
    openTime: '7:30 AM',
    closeTime: '11:30 PM',
    image: 'https://via.placeholder.com/150/F57C00/white?text=NM',
    services: ['24-hour Delivery', 'Prescription Upload', 'Generic Alternatives', 'Baby Care'],
  },
  {
    id: 'ms6',
    name: 'PharmEasy Express',
    address: '89, Whitefield Main Road, Bangalore - 560066',
    distance: '2.3 km',
    rating: 4.5,
    phone: '+91-80-65678945',
    isOpen: false,
    openTime: '9:00 AM',
    closeTime: '8:00 PM',
    image: 'https://via.placeholder.com/150/0288D1/white?text=PE',
    services: ['Quick Delivery', 'Subscription Service', 'Lab Tests', 'Doctor Consultation'],
  },
  {
    id: 'ms7',
    name: 'Rashmi Medical Store',
    address: '34, Malleshwaram 18th Cross, Bangalore - 560003',
    distance: '3.1 km',
    rating: 4.0,
    phone: '+91-80-75678956',
    isOpen: true,
    openTime: '8:00 AM',
    closeTime: '9:00 PM',
    image: 'https://via.placeholder.com/150/388E3C/white?text=RS',
    services: ['Local Delivery', 'Prescription Medicines', 'Health Devices', 'Surgical Items'],
  },
  {
    id: 'ms8',
    name: 'Janaushadhi Kendram',
    address: '12, Rajajinagar, Bangalore - 560010',
    distance: '3.5 km',
    rating: 4.1,
    phone: '+91-80-85678967',
    isOpen: true,
    openTime: '9:00 AM',
    closeTime: '6:00 PM',
    image: 'https://via.placeholder.com/150/C62828/white?text=JK',
    services: ['Affordable Generics', 'Government Scheme', 'Prescription Medicines'],
  },
];

// ============================================
// HEALTH PACKAGES DATA
// ============================================

export const HEALTH_PACKAGES: HealthPackage[] = [
  {
    id: 'hp1',
    name: 'Full Body Checkup',
    category: 'Comprehensive',
    description: 'Comprehensive 65-parameter health checkup covering blood, urine, thyroid, liver, kidney, vitamins, and cardiac markers.',
    tests: ['CBC', 'Blood Sugar', 'Lipid Profile', 'LFT', 'KFT', 'Thyroid Profile', 'Vitamin D', 'Vitamin B12', 'ECG', 'Urine Routine', 'Chest X-Ray'],
    price: 2999,
    originalPrice: 4999,
    discountPercent: 40,
    discountedPrice: 2999,
    reportTime: '48 hours',
    image: 'https://via.placeholder.com/150/0066CC/white?text=FBC',
    isPopular: true,
  },
  {
    id: 'hp2',
    name: 'Diabetes Care Package',
    category: 'Essential',
    description: 'Targeted package for diabetes monitoring with blood sugar, HbA1c, kidney function, and related parameters.',
    tests: ['Fasting Blood Sugar', 'Post Prandial Sugar', 'HbA1c', 'Urine Microalbumin', 'KFT', 'Lipid Profile', 'Insulin Fasting'],
    price: 1625,
    originalPrice: 2500,
    discountPercent: 35,
    discountedPrice: 1625,
    reportTime: '12 hours',
    image: 'https://via.placeholder.com/150/FF9800/white?text=DCP',
    isPopular: true,
  },
  {
    id: 'hp3',
    name: 'Heart Health Package',
    category: 'Premium',
    description: 'Complete cardiac risk assessment including ECG, ECHO, stress test, and blood biomarkers.',
    tests: ['Lipid Profile', 'ECG', 'Cardiac Risk Markers', 'hs-CRP', 'Homocysteine', 'HbA1c', 'CBC'],
    price: 2450,
    originalPrice: 3500,
    discountPercent: 30,
    discountedPrice: 2450,
    reportTime: '24 hours',
    image: 'https://via.placeholder.com/150/F44336/white?text=HHP',
    isPopular: true,
  },
  {
    id: 'hp4',
    name: 'Women\'s Wellness Package',
    category: "Women's",
    description: 'Comprehensive health checkup designed for women including thyroid, hormone levels, pap smear, and bone density.',
    tests: ['CBC', 'Thyroid Profile', 'Hormone Panel (FSH, LH, Estrogen)', 'Vitamin D', 'Iron Studies', 'Pap Smear', 'Mammography'],
    price: 3575,
    originalPrice: 5500,
    discountPercent: 35,
    discountedPrice: 3575,
    reportTime: '72 hours',
    image: 'https://via.placeholder.com/150/E91E63/white?text=WWP',
    isPopular: false,
  },
  {
    id: 'hp5',
    name: 'Vitamin Deficiency Panel',
    category: 'Basic',
    description: 'Check essential vitamin and mineral levels including D, B12, B9, Iron, Zinc, and Calcium.',
    tests: ['Vitamin D', 'Vitamin B12', 'Folic Acid', 'Iron Studies', 'Zinc', 'Calcium', 'Magnesium'],
    price: 2400,
    originalPrice: 3200,
    discountPercent: 25,
    discountedPrice: 2400,
    reportTime: '24 hours',
    image: 'https://via.placeholder.com/150/8BC34A/white?text=VDP',
    isPopular: true,
  },
  {
    id: 'hp6',
    name: 'Senior Citizen Package (60+)',
    category: 'Senior',
    description: 'Tailored health check for seniors covering joint health, kidney, cardiac, blood, and neurological markers.',
    tests: ['CBC', 'Blood Sugar', 'LFT', 'KFT', 'Lipid Profile', 'Thyroid', 'ECG', 'Bone Density (DEXA)', 'Prostate (PSA for men)', 'Chest X-Ray'],
    price: 3300,
    originalPrice: 6000,
    discountPercent: 45,
    discountedPrice: 3300,
    reportTime: '72 hours',
    image: 'https://via.placeholder.com/150/607D8B/white?text=SCP',
    isPopular: false,
  },
];

// ============================================
// SAMPLE APPOINTMENTS
// ============================================

export const SAMPLE_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt1',
    doctorId: 'd1',
    doctor: DOCTORS[0],
    patientName: 'John Doe',
    date: '2024-02-15',
    time: '10:00 AM',
    status: 'Upcoming',
    type: 'In-Clinic',
    amount: 800,
    symptoms: 'Chest pain, breathlessness',
    paymentId: 'pay_test_123',
  },
  {
    id: 'apt2',
    doctorId: 'd3',
    doctor: DOCTORS[2],
    patientName: 'John Doe',
    date: '2024-01-20',
    time: '09:00 AM',
    status: 'Completed',
    type: 'In-Clinic',
    amount: 400,
    symptoms: 'Fever, cold',
    prescription: {
      id: 'prx1',
      appointmentId: 'apt2',
      doctorName: 'Dr. Rajesh Kumar',
      date: '2024-01-20',
      medicines: [
        { name: 'Paracetamol 500mg', dosage: '1 tablet', duration: '5 days', instructions: 'After meals' },
        { name: 'Cetirizine 10mg', dosage: '1 tablet', duration: '5 days', instructions: 'At night' },
      ],
      notes: 'Rest for 3 days, drink plenty of fluids',
      followUp: '2024-01-27',
    },
    paymentId: 'pay_test_456',
  },
  {
    id: 'apt3',
    doctorId: 'd2',
    doctor: DOCTORS[1],
    patientName: 'John Doe',
    date: '2024-02-01',
    time: '11:00 AM',
    status: 'Cancelled',
    type: 'Video',
    amount: 600,
    paymentId: 'pay_test_789',
  },
];

// ============================================
// NOTIFICATIONS DATA
// ============================================

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    title: 'Appointment Reminder',
    message: 'Your appointment with Dr. Arjun Mehta is tomorrow at 10:00 AM at Apollo Hospitals.',
    type: 'appointment',
    isRead: false,
    createdAt: '2024-02-14T10:00:00Z',
  },
  {
    id: 'n2',
    title: 'Order Shipped!',
    message: 'Your order of Dolo 650 and Vitamin D3 has been shipped and will be delivered by tomorrow.',
    type: 'order',
    isRead: false,
    createdAt: '2024-02-13T15:30:00Z',
  },
  {
    id: 'n3',
    title: 'Lab Report Ready',
    message: 'Your CBC report is now available. Download it from the Health Records section.',
    type: 'lab',
    isRead: true,
    createdAt: '2024-02-12T09:00:00Z',
  },
  {
    id: 'n4',
    title: 'Health Tip',
    message: 'Stay hydrated! Drink at least 8 glasses of water every day for better health.',
    type: 'general',
    isRead: true,
    createdAt: '2024-02-11T08:00:00Z',
  },
  {
    id: 'n5',
    title: 'Exclusive Offer',
    message: 'Get 30% off on all lab tests this weekend. Book now and save!',
    type: 'general',
    isRead: false,
    createdAt: '2024-02-10T12:00:00Z',
  },
];

// ============================================
// BANNERS DATA
// ============================================

export const BANNERS: Banner[] = [
  {
    id: 'b1',
    title: 'Book Lab Tests',
    subtitle: 'Get 25% off on your first lab test. Results in 6 hours!',
    image: 'lab',
    color: '#0066CC',
    actionText: 'Book Now',
  },
  {
    id: 'b2',
    title: 'Consult Top Doctors',
    subtitle: 'Connect with 500+ verified specialists from home',
    image: 'doctor',
    color: '#00A86B',
    actionText: 'Find Doctor',
  },
  {
    id: 'b3',
    title: 'Medicines Delivered',
    subtitle: 'Order medicines online. Delivered in 2 hours',
    image: 'medicine',
    color: '#7B1FA2',
    actionText: 'Order Now',
  },
  {
    id: 'b4',
    title: 'Full Body Checkup',
    subtitle: '65 tests at ₹2999 only. Free home sample collection',
    image: 'checkup',
    color: '#F57C00',
    actionText: 'Book Package',
  },
];
